server:
  port: 9090

spring:
  application:
    name: gateway-auth

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway-auth
            client-secret: WE0SNHTyiKuPRckYsCYHGfrSSCpnM0Lx
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/narosco
  cloud:
    gateway:
      routes:
        - id: test-api
          uri: http://localhost:8081
          predicates:
            - Path=/test/**
          filters:
            - TokenRelay=
